### ISSUE TITLE
i can not recieve  disconnected state .is it my problem ?

### ISSUE THREAD

**Issue by xhsiung** [hiram3512/HiSocket#1]
i try to connect and disconnect
i can not recieve state when it disconneted

**Comment by xhsiung** [comment]
> description
i try to connect and disconnect 
i can not recieve state when it disconneted

**Comment by hiram3512** [comment]
thanks for your feedback, have added disconnect state to source code, you can update to newest version check this function.
```csharp      
 public override void DisConnect()
        {
            ChangeState(SocketState.DisConnected);
            base.DisConnect();
        }
```

**Comment by xhsiung** [comment]
Sorry , my description is something wrong .
when i  start  "mono TestServer", i can see the connnect message .
Suddenly , "mono TestServer is crash (it disconnected)" , i can not see message in unity .

**Comment by hiram3512** [comment]
- if you initiative disconnect to server, disconnected event will be fire.
-  when server shutdown, you should use heart message to check this situation by yourself because of tcp protocol's feature.
- or you can use socket.pool to check if still available.
- more info is here https://stackoverflow.com/questions/2661764/how-to-check-if-a-socket-is-connected-disconnected-in-c
